### ISSUE TITLE
wp-secrets.php only contains <?php

### ISSUE THREAD

**Issue by cocoonkid** [nidr0x/docker-production-wordpress#7]
wp-secrets.php only contains <?php

Is this intended?

**Comment by gnowland** [comment]
Hi, yes as you can see in https://github.com/nidr0x/docker-production-wordpress/blob/58bfbaecd9976f019ad3596c536e383c90e5c59f/entrypoint.sh#L5 the contents of that file are replaced with the output of the `curl` request to https://api.wordpress.org/secret-key/1.1/salt/.

**Comment by cocoonkid** [comment]
thanks!
