### ISSUE TITLE
Add more instructions in readme

### ISSUE THREAD

**Issue by lindesvard** [nidr0x/docker-production-wordpress#9]
Hi,

This repo seems so promising for my use case. Does not really know how to get going locally and how I do with the docker-compose to mount a local volume. For example the `wp-content`.

Would be neat to have some documentation how to set everything up locally and production. I know this repo is focused for production but would be nice to have some instructions.

Thanks for a promising repo at least 🎉

**Comment by marctorresbcn** [comment]
Hi, Could the http2 protocol not be activated?

I would appreciate a little more information in the readme file. Thank you.

**Comment by otaprochazka** [comment]
I just spent some time dicovering that some folders needs to be manualy created in wp-content forlder to be able to properly install WP templates (plugins, themes, upgrade, uploads)
